export const initialState = {
  user: null,
  searchTerm: "",
  filterTerm: "all",
  artists: null,
  artistFilter: null,
  languageFilter: null,
  yearFilter: null,
  allUsers: null,
  allSongs: null,
  allSuggestedSongs: null,
  allAlbums: null,
  albumFilter: null,
  song: 0,
  suggestedSong: 0,
  isSongPlaying: false,
  miniPlayer: false,
  currentTime:0,
};
